### ISSUE TITLE
GNOME 46 support

### ISSUE THREAD

**Issue by RedBearAK** [flexagoon/focused-window-dbus#5]
@flexagoon 

I installed the extension in Fedora 40 Workstation (pre-beta, it just branched off the Rawhide development train and became its own thing a couple of weeks ago, with nightly ISOs available, and has GNOME 46.rc). I was able to install it with Extension Manager even though it said "Unsupported", then edited the `metadata.json` to add "46" to the shell versions list. 

Seems to work with no errors, as I expected, since I don't think much is changing in GNOME 46. 

If you could make the change and publish it, my users who may start testing Fedora 40 beta, which should be announced soon, will have an easier time finding the extension (without needing to enable "Show Unsupported" from the Extension Manager hamburger menu), and thus getting my keymapper-based project (Toshy) to work in GNOME 46. 

Doesn't look like any kind of "porting" needs to be done this time. 

Fedora is usually a convenient way to get a look at the next GNOME release if you think you need to test something. Nightly ISOs for Workstation are here: 

https://dl.fedoraproject.org/pub/fedora/linux/development/40/Workstation/x86_64/iso/

Thanks for your time!

**Comment by flexagoon** [comment]
@RedBearAK thanks a lot for testing! Sure, I'll add Gnome 46 to supported version list.

I can't really install nightly Fedora ISOs because I'm using a custom Silverblue image rather than upstream Fedora.

Btw, I can probably give you commit rights to this repo if you want, since it seems like you're always testing new Fedora versions, it'll probably be faster for you to just add the gnome version to the manifest instead of making an issue and waiting for me to add it.

**Comment by RedBearAK** [comment]
@flexagoon 

> Btw, I can probably give you commit rights to this repo if you want, since it seems like you're always testing new Fedora versions, it'll probably be faster for you to just add the gnome version to the manifest instead of making an issue and waiting for me to add it.

Thanks, but you’d still need to be the one submitting it to the extension site maintainers. There’s certainly no hurry this early in the game. I’ll submit a PR for G47 in about six months. 😂 🤙
